### ISSUE TITLE
Add labels to annotation MANIFEST files to indicate JBrowse indexing

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/datastore-issues#218]
In annotation MANIFEST files of selected **annotation collections**[1], add a "jbrowse-index" value under the "applications" key, for gene_models_main.gff3.gz files. The purpose is to indicate which tracks should be indexed to permit search-by-name in JBrowse.

[1] The addition of this flag/key need not be added to every annotation collection. For Glycine, the consensus of the SoyBase team is to index only the designated reference accessions: FiskebyIII, Hwangkeum, JD17, Lee, Wm82, Zh13 (13 collections currently, including all assembly and annotation versions).

For example:
```
- name: glyma.Zh13.gnm2.ann1.FJ3G.gene_models_main.gff3.gz
  description: Gene models - main
  applications:
   - mines
   - jbrowse-index
```
